package com.amazon.gdpr.util;

/****************************************************************************************
 * This Class contains all the Queries that is required through out the project 
 ****************************************************************************************/
public class SqlQueriesConstant {
	
	public static int BATCH_ROW_COUNT = 1000;
	
	public static String RUNMGMT_LAST_RUN 	= "SELECT RUN_ID, RUN_STATUS FROM GDPR.RUN_MGMT ORDER BY RUN_ID DESC LIMIT 1";
	
	public static String RUNMGMT_INSERT_RUN = "INSERT INTO GDPR.RUN_MGMT(RUN_NAME, RUN_STATUS, RUN_START_DATE_TIME) VALUES( "
			+ "?, ?, CURRENT_TIMESTAMP)";
	
	public static String RUNMGMT_INSERT_QRY	= "INSERT INTO GDPR.RUN_MGMT(RUN_NAME, RUN_STATUS) VALUES(?, ?) "
			+ "ON DUPLICATE KEY UPDATE RUN_NAME=VALUES(RUN_NAME), RUN_ID=LAST_INSERT_ID(RUN_ID)";
		
	public static String RUN_MODULE_MGMT_INSERT	= "INSERT INTO GDPR.RUN_MODULE_MGMT (RUN_ID, MODULE_NAME, MODULE_STATUS, MODULE_START_DATE_TIME, "
			+ " MODULE_END_DATE_TIME, MODULE_COMMENTS ) VALUES (?, ?, ?, ?, ?, ?)";			
	
	public static String CATEGORY_FETCH		= "SELECT CATEGORY_ID, CATEGORY_NAME, STATUS FROM "
			+ "GDPR.CATEGORY WHERE STATUS IN ('ACTIVE')";
	
	public static String IMPACT_TABLE_FETCH	= "SELECT IMPACT_TABLE_ID, IMPACT_TABLE_NAME, PARENT_TABLE_NAME, "
			+ "IMPACT_TABLE_COLUMN, PARENT_TABLE_COLUMN FROM GDPR.IMPACT_TABLE ";
	
	public static String IMPACT_FIELD_FETCH = "SELECT IMPACT_FIELD_ID, IMPACT_TABLE_ID, IMPACT_FIELD_LABEL, "
			+ " IMPACT_FIELD_NAME, IMPACT_FIELD_TYPE FROM GDPR.IMPACT_FIELD";
	
	public static String ANONYMIZATION_DETAIL_FETCH = "SELECT IMPACT_FIELD_ID, "
			+ " CATEGORY_ID, REGION, COUNTRY_CODE, TRANSFORMATION_TYPE, STATUS FROM GDPR.ANONYMIZATION_DETAIL";
			
	public static String SUMMARY_DATA_FETCH = 
			"SELECT DISTINCT AD.CATEGORY_ID CATEGORY_ID, AD.REGION REGION, AD.COUNTRY_CODE COUNTRY_CODE, "
			+" IT.IMPACT_TABLE_NAME IMPACT_TABLE_NAME, IF.IMPACT_FIELD_NAME IMPACT_FIELD_NAME, IF.IMPACT_FIELD_TYPE IMPACT_FIELD_TYPE, "
			+" AD.TRANSFORMATION_TYPE TRANSFORMATION_TYPE, IF.IMPACT_TABLE_ID IMPACT_TABLE_ID FROM "
			+" GDPR.ANONYMIZATION_DETAIL AD, GDPR.IMPACT_FIELD IF, GDPR.IMPACT_TABLE IT, GDPR.CATEGORY CAT, GDPR.COUNTRY CTY "
			+" WHERE AD.IMPACT_FIELD_ID = IF.IMPACT_FIELD_ID AND IF.IMPACT_TABLE_ID =IT.IMPACT_TABLE_ID "
			+" AND CAT.CATEGORY_ID = AD.CATEGORY_ID AND (AD.REGION = CTY.REGION OR AD.COUNTRY_CODE = CTY.COUNTRY_CODE) "
			+" AND AD.STATUS = 'ACTIVE' AND CAT.STATUS = 'ACTIVE' AND CTY.STATUS = 'ACTIVE' "
			+" AND AD.ANONYMIZATION_DETAIL_ID IN (SELECT ANONYMIZATION_DETAIL_ID FROM GDPR.RUN_ANONYMIZATION WHERE RUN_ID = ?) "
			+" ORDER BY AD.CATEGORY_ID, AD.REGION, AD.COUNTRY_CODE, IF.IMPACT_TABLE_ID ";
		
	public static String IMPACT_FIELD_INSERT = "INSERT INTO GDPR.IMPACT_FIELD (IMPACT_TABLE_ID, "
			+ " IMPACT_FIELD_LABEL, IMPACT_FIELD_NAME, IMPACT_FIELD_TYPE) VALUES (?, ?, ?, ?)";
	
	public static String ANONYMIZATION_DETAIL_INSERT = "INSERT INTO GDPR.ANONYMIZATION_DETAIL "
			+ " (IMPACT_FIELD_ID, CATEGORY_ID, REGION, COUNTRY_CODE, TRANSFORMATION_TYPE, STATUS) "
			+ " VALUES (?, ?, ?, ?, ?, ?)";
	
	public static String RUN_ANONYMIZATION_INSERT = "INSERT INTO GDPR.RUN_ANONYMIZATION (RUN_ID, ANONYMIZATION_DETAIL_ID) "
			+ " SELECT ?, ANONYMIZATION_DETAIL_ID FROM GDPR.ANONYMIZATION_DETAIL WHERE STATUS = 'ACTIVE'";
	
	public static String RUN_ERROR_MGMT_INSERT = "INSERT INTO GDPR.RUN_ERROR_MGMT (RUN_ID, ERROR_SUMMARY, ERROR_DETAIL ) "
			+ "VALUES (?, ?, ?) ";
	
	public static String RUN_SUMMARY_MGMT_INSERT = "INSERT INTO GDPR.RUN_SUMMARY_MGMT (RUN_ID, CATEGORY_ID, REGION, COUNTRY_CODE, "
			+ " IMPACT_TABLE_ID, BACKUP_QUERY, DEPERSONALIZATION_QUERY) VALUES (?,?,?,?, ?,?,?) ";
	/*****Backup Table Processor Code Change Starts***/
	public static String BACKUPTABLE_COLUMNS_QRY	= "SELECT TABLE_NAME,COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE LOWER(TABLE_SCHEMA)=LOWER('GDPR') AND TABLE_NAME LIKE LOWER('%BKP_%')";
	public static String IMPACTTABLE_DETAILS_QRY	= "SELECT T1.IMPACT_TABLE_NAME, T2.IMPACT_FIELD_NAME,  T2.IMPACT_FIELD_TYPE FROM  GDPR.IMPACT_TABLE T1 JOIN  GDPR.IMPACT_FIELD T2 ON T1.IMPACT_TABLE_ID = T2.IMPACT_TABLE_ID;";
	/*****Backup Table Processor Code Change Ends***/
		
	public static String GDPR_DEPERSONALIZATION_FETCH = "SELECT CANDIDATE__C, BGC_Application__c, CATEGORY__C, COUNTRY_CODE__C, "
			+ "BGC_STATUS__C, PH_AMAZON_ASSESSMENT_STATUS__C, PH_CANDIDATE_PROVIDED_STATUS__C, PH_MASTER_DATA_STATUS__C, "
			+ "PH_WITH_CONSENT_STATUS__C FROM SALESFORCE.GDPR_DEPERSONALIZATION__C "
			+ "WHERE BGC_STATUS__C = 'Cleared' OR PH_AMAZON_ASSESSMENT_STATUS__C = 'Cleared'";
	
	public static String GDPR_DEPERSONALIZATION_INPUT = "INSERT INTO GDPR.GDPR_DEPERSONALIZATION (CANDIDATE__C, CATEGORY_ID, COUNTRY_CODE, HVH_STATUS, "
			+ "HEROKU_STATUS) VALUES (?, ?, ?, ?, ?)";
	
}